language: php
php:
  - '5.6'

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev

script:
- ./vendor/bin/phpunit --configuration phpunit.xml

after_script:
- php vendor/bin/coveralls -v