language: php
php:
  - '5.6'

before_install:
- composer require --dev phpunit/phpunit:4.8.* satooshi/php-coveralls:^2.0
- composer install --dev

script:
- ./vendor/bin/phpunit --configuration phpunit.xml

after_script:
- php ./vendor/bin/coveralls -v